name: watertap-electrodialysis-bipolar-tea
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pip:
    - alabaster==0.7.16
    - annotated-types==0.7.0
    - anyio==4.9.0
    - argon2-cffi==23.1.0
    - argon2-cffi-bindings==21.2.0
    - arrow==1.3.0
    - astroid==2.15.8
    - asttokens==3.0.0
    - async-lru==2.0.5
    - attrs==25.3.0
    - babel==2.17.0
    - beautifulsoup4==4.13.3
    - black==24.3.0
    - bleach==6.2.0
    - certifi==2025.1.31
    - cffi==1.17.1
    - cfgv==3.4.0
    - charset-normalizer==3.4.1
    - click==8.1.8
    - colorama==0.4.6
    - comm==0.2.2
    - contourpy==1.3.1
    - coverage==7.8.0
    - cryptography==44.0.2
    - cycler==0.12.1
    - debugpy==1.8.13
    - decorator==5.2.1
    - defusedxml==0.7.1
    - dill==0.3.9
    - distlib==0.3.9
    - docutils==0.20.1
    - executing==2.2.0
    - fastjsonschema==2.21.1
    - filelock==3.18.0
    - flexcache==0.3
    - flexparser==0.4
    - fonttools==4.57.0
    - fqdn==1.5.1
    - h11==0.14.0
    - h5py==3.13.0
    - httpcore==1.0.7
    - httpx==0.28.1
    - idaes-flowsheet-processor==0.1.dev4
    - idaes-pse==2.6.0
    - identify==2.6.9
    - idna==3.10
    - imagesize==1.4.1
    - importlib_resources==6.5.2
    - iniconfig==2.1.0
    - ipykernel==6.29.5
    - ipython==9.0.2
    - ipython_pygments_lexers==1.1.1
    - ipywidgets==8.1.5
    - isoduration==20.11.0
    - isort==5.13.2
    - jedi==0.19.2
    - Jinja2==3.0.3
    - json5==0.12.0
    - jsonpointer==3.0.0
    - jsonschema==4.23.0
    - jsonschema-specifications==2024.10.1
    - jupyter==1.1.1
    - jupyter_client==8.6.3
    - jupyter-console==6.6.3
    - jupyter_core==5.7.2
    - jupyter-events==0.12.0
    - jupyter-lsp==2.2.5
    - jupyter_server==2.15.0
    - jupyter_server_terminals==0.5.3
    - jupyterlab==4.3.6
    - jupyterlab_pygments==0.3.0
    - jupyterlab_server==2.27.3
    - jupyterlab_widgets==3.0.13
    - kiwisolver==1.4.8
    - lazy-object-proxy==1.10.0
    - linkify-it-py==2.0.3
    - MarkupSafe==3.0.2
    - matplotlib==3.10.1
    - matplotlib-inline==0.1.7
    - mccabe==0.7.0
    - mistune==3.1.3
    - mpmath==1.3.0
    - mypy-extensions==1.0.0
    - nbclient==0.10.2
    - nbconvert==7.16.6
    - nbformat==5.10.4
    - nbmake==1.5.5
    - nbsphinx==0.9.7
    - nest-asyncio==1.6.0
    - networkx==3.4.2
    - nodeenv==1.9.1
    - notebook==7.3.3
    - notebook_shim==0.2.4
    - numpy==2.2.4
    - overrides==7.7.0
    - packaging==24.2
    - pandas==2.2.3
    - pandocfilters==1.5.1
    - parameter-sweep==0.1.0
    - parso==0.8.4
    - pathspec==0.12.1
    - pillow==11.1.0
    - Pint==0.24.4
    - pip==25.0
    - platformdirs==4.3.7
    - pluggy==1.5.0
    - ply==3.11
    - pre_commit==4.2.0
    - prometheus_client==0.21.1
    - prompt_toolkit==3.0.50
    - psutil==7.0.0
    - pure_eval==0.2.3
    - pycparser==2.22
    - pydantic==2.11.2
    - pydantic_core==2.33.1
    - Pygments==2.19.1
    - pylint==2.17.7
    - pyomo==6.9.1
    - pyparsing==3.2.3
    - pytest==8.3.5
    - pytest-cov==6.1.0
    - python-dateutil==2.9.0.post0
    - python-json-logger==3.3.0
    - pytz==2025.2
    # - pywin32==310
    # - pywinpty==2.0.15
    - PyYAML==6.0.2
    - pyzmq==26.3.0
    - referencing==0.36.2
    - requests==2.32.3
    - rfc3339-validator==0.1.4
    - rfc3986-validator==0.1.1
    - rpds-py==0.24.0
    - scipy==1.15.2
    - Send2Trash==1.8.3
    - setuptools==75.8.0
    - six==1.17.0
    - sniffio==1.3.1
    - snowballstemmer==2.2.0
    - soupsieve==2.6
    - Sphinx==7.1.2
    - sphinx-rtd-theme==3.0.2
    - sphinxcontrib-applehelp==2.0.0
    - sphinxcontrib-devhelp==2.0.0
    - sphinxcontrib-htmlhelp==2.1.0
    - sphinxcontrib-jquery==4.1
    - sphinxcontrib-jsmath==1.0.1
    - sphinxcontrib-qthelp==2.0.0
    - sphinxcontrib-serializinghtml==2.0.0
    - stack-data==0.6.3
    - sympy==1.13.3
    - terminado==0.18.1
    - tinycss2==1.4.0
    - tomlkit==0.13.2
    - tornado==6.4.2
    - traitlets==5.14.3
    - types-python-dateutil==2.9.0.20241206
    - typing_extensions==4.13.1
    - typing-inspection==0.4.0
    - tzdata==2025.2
    - uc-micro-py==1.0.3
    - uri-template==1.3.0
    - urllib3==1.26.20
    - virtualenv==20.30.0
    - watertap==1.1.0
    - watertap-solvers==24.12.9
    - wcwidth==0.2.13
    - webcolors==24.11.1
    - webencodings==0.5.1
    - websocket-client==1.8.0
    - wheel==0.45.1
    - widgetsnbextension==4.0.13
    - wrapt==1.17.2
