name: Reproduce analysis

on:
  push:
  # commented while WIP to avoid running workflows twice for PR #1
  # pull_request:
  #   branches: ['*']
 
defaults:
  run:
    # -l: login shell, needed when using Conda:
    shell: bash -l {0}

jobs:

  scripts:
    name: Install dependencies and run scripts (${{ matrix.os }})

    strategy:
      fail-fast: false
      matrix:
        os:
          - linux
          - win64
          # - macos
        include:
          - os: linux
            runner-image: ubuntu-24.04
          - os: win64
            runner-image: windows-2022

    runs-on: ${{ matrix.runner-image }}

    steps:
      - uses: actions/checkout@v4

      - uses: conda-incubator/setup-miniconda@v3
        with:
          environment-file: environment.yml
          activate-environment: watertap-electrodialysis-bipolar-tea
          miniforge-version: latest
          conda-remove-defaults: true

      - name: Display installed version
        run: |
          pip show pyomo idaes-pse watertap watertap-solvers parameter-sweep

      - name: Install IDAES solvers (Linux)
        if: matrix.os == 'linux'
        run: |
          # ensure system dependencies are installed (required on GHA starting from ubuntu-24.04)
          if [ -f "/etc/os-release" ]; then
            . /etc/os-release
            if [ "$ID" = "ubuntu" ] ; then
            echo '::group::Output of "apt install" for required OS packages'
            sudo apt install libgfortran5 libgomp1 liblapack3 libblas3
            echo '::endgroup::'
            fi
          fi

          # --distro ubuntu2204 must be specified since the version of IDAES pinned in the environment
          # does not have dedicated builds for ubuntu 24.04
          idaes get-extensions --verbose --distro ubuntu2204

      - name: Install IDAES solvers
        if: matrix.os != 'linux'
        run: |
          idaes get-extensions --verbose

      - name: Run BPED_sample_script.py
        run: |
          python BPED_sample_script.py
