name: Reproduce analysis

on:
  push:
 
defaults:
  run:
    # -l: login shell, needed when using Conda:
    shell: bash -l {0}

jobs:

  scripts:
    name: Install dependencies and run scripts
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - uses: conda-incubator/setup-miniconda@v3
        with:
          environment-file: environment.yml
          activate-environment: watertap-electrodialysis-bipolar-tea
          miniforge-version: latest
          conda-remove-defaults: true

      - name: Display installed version
        run: |
          pip show pyomo idaes-pse watertap watertap-solvers parameter-sweep

      - name: Install IDAES solvers
        run: |
          # extra dependencies must be installed on Ubuntu 24.04 and later
          if [ -f "/etc/os-release" ]; then
            . /etc/os-release
            if [ "$ID" = "ubuntu" ] ; then
            echo '::group::Output of "apt install" for required OS packages'
            sudo apt install libgfortran5 libgomp1 liblapack3 libblas3
            echo '::endgroup::'
            fi
          fi

          # --distro ubuntu2204 must be specified since the version of IDAES pinned in the environment
          # does not have dedicated builds for ubuntu 24.04
          idaes get-extensions --verbose --distro ubuntu2204

      - name: Run BPED_sample_script.py
        run: |
          python BPED_sample_script.py
